-- Create the subs table for subscription/payment tracking (wallet address -> expiry).
-- Run this in Supabase SQL Editor (Dashboard -> SQL Editor) if you see:
--   "Could not find the table 'public.subs' in the schema cache"

CREATE TABLE IF NOT EXISTS public.subs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address TEXT NOT NULL,
  amount NUMERIC,
  expires TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_subs_address ON public.subs (address);
CREATE INDEX IF NOT EXISTS idx_subs_expires ON public.subs (expires);

-- Optional: allow anonymous read for get-sub (or use RLS with your auth)
ALTER TABLE public.subs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read for anon"
  ON public.subs FOR SELECT
  TO anon
  USING (true);

CREATE POLICY "Allow insert for anon"
  ON public.subs FOR INSERT
  TO anon
  WITH CHECK (true);
